// GENERATED by matlab/gen_atan_lut.m -- do not edit by hand.
//
// cordic_atan32(i) = round(atan(2^-i) / pi * 2^31)   binary angle, pi == 2^31
// cordic_invk32(n) = round(2^32 / K_n)               K_n = prod_{i<n} sqrt(1 + 2^-2i)
//
// Functions rather than localparam arrays: Icarus Verilog does not accept
// '{...} initialisers on unpacked arrays. Include inside a module body.

function automatic [31:0] cordic_atan32(input integer i);
  case (i)
     0: cordic_atan32 = 32'd536870912 ; // 0.785398163397 rad
     1: cordic_atan32 = 32'd316933406 ; // 0.463647609001 rad
     2: cordic_atan32 = 32'd167458907 ; // 0.244978663127 rad
     3: cordic_atan32 = 32'd85004756  ; // 0.124354994547 rad
     4: cordic_atan32 = 32'd42667331  ; // 0.062418809996 rad
     5: cordic_atan32 = 32'd21354465  ; // 0.031239833430 rad
     6: cordic_atan32 = 32'd10679838  ; // 0.015623728620 rad
     7: cordic_atan32 = 32'd5340245   ; // 0.007812341060 rad
     8: cordic_atan32 = 32'd2670163   ; // 0.003906230132 rad
     9: cordic_atan32 = 32'd1335087   ; // 0.001953122516 rad
    10: cordic_atan32 = 32'd667544    ; // 0.000976562190 rad
    11: cordic_atan32 = 32'd333772    ; // 0.000488281211 rad
    12: cordic_atan32 = 32'd166886    ; // 0.000244140620 rad
    13: cordic_atan32 = 32'd83443     ; // 0.000122070312 rad
    14: cordic_atan32 = 32'd41722     ; // 0.000061035156 rad
    15: cordic_atan32 = 32'd20861     ; // 0.000030517578 rad
    16: cordic_atan32 = 32'd10430     ; // 0.000015258789 rad
    17: cordic_atan32 = 32'd5215      ; // 0.000007629395 rad
    18: cordic_atan32 = 32'd2608      ; // 0.000003814697 rad
    19: cordic_atan32 = 32'd1304      ; // 0.000001907349 rad
    20: cordic_atan32 = 32'd652       ; // 0.000000953674 rad
    21: cordic_atan32 = 32'd326       ; // 0.000000476837 rad
    22: cordic_atan32 = 32'd163       ; // 0.000000238419 rad
    23: cordic_atan32 = 32'd81        ; // 0.000000119209 rad
    24: cordic_atan32 = 32'd41        ; // 0.000000059605 rad
    25: cordic_atan32 = 32'd20        ; // 0.000000029802 rad
    26: cordic_atan32 = 32'd10        ; // 0.000000014901 rad
    27: cordic_atan32 = 32'd5         ; // 0.000000007451 rad
    28: cordic_atan32 = 32'd3         ; // 0.000000003725 rad
    29: cordic_atan32 = 32'd1         ; // 0.000000001863 rad
    30: cordic_atan32 = 32'd1         ; // 0.000000000931 rad
    31: cordic_atan32 = 32'd0         ; // 0.000000000466 rad
    default: cordic_atan32 = 32'd0;
  endcase
endfunction

function automatic [31:0] cordic_invk32(input integer n);
  case (n)
     1: cordic_invk32 = 32'd3037000500; // 1/K = 0.707106781187
     2: cordic_invk32 = 32'd2716375826; // 1/K = 0.632455532034
     3: cordic_invk32 = 32'd2635271635; // 1/K = 0.613571991078
     4: cordic_invk32 = 32'd2614921743; // 1/K = 0.608833912518
     5: cordic_invk32 = 32'd2609829388; // 1/K = 0.607648256256
     6: cordic_invk32 = 32'd2608555990; // 1/K = 0.607351770141
     7: cordic_invk32 = 32'd2608237621; // 1/K = 0.607277644094
     8: cordic_invk32 = 32'd2608158028; // 1/K = 0.607259112299
     9: cordic_invk32 = 32'd2608138129; // 1/K = 0.607254479333
    10: cordic_invk32 = 32'd2608133154; // 1/K = 0.607253321090
    11: cordic_invk32 = 32'd2608131911; // 1/K = 0.607253031529
    12: cordic_invk32 = 32'd2608131600; // 1/K = 0.607252959139
    13: cordic_invk32 = 32'd2608131522; // 1/K = 0.607252941041
    14: cordic_invk32 = 32'd2608131503; // 1/K = 0.607252936517
    15: cordic_invk32 = 32'd2608131498; // 1/K = 0.607252935386
    16: cordic_invk32 = 32'd2608131497; // 1/K = 0.607252935103
    17: cordic_invk32 = 32'd2608131496; // 1/K = 0.607252935032
    18: cordic_invk32 = 32'd2608131496; // 1/K = 0.607252935015
    19: cordic_invk32 = 32'd2608131496; // 1/K = 0.607252935010
    20: cordic_invk32 = 32'd2608131496; // 1/K = 0.607252935009
    21: cordic_invk32 = 32'd2608131496; // 1/K = 0.607252935009
    22: cordic_invk32 = 32'd2608131496; // 1/K = 0.607252935009
    23: cordic_invk32 = 32'd2608131496; // 1/K = 0.607252935009
    24: cordic_invk32 = 32'd2608131496; // 1/K = 0.607252935009
    25: cordic_invk32 = 32'd2608131496; // 1/K = 0.607252935009
    26: cordic_invk32 = 32'd2608131496; // 1/K = 0.607252935009
    27: cordic_invk32 = 32'd2608131496; // 1/K = 0.607252935009
    28: cordic_invk32 = 32'd2608131496; // 1/K = 0.607252935009
    29: cordic_invk32 = 32'd2608131496; // 1/K = 0.607252935009
    30: cordic_invk32 = 32'd2608131496; // 1/K = 0.607252935009
    31: cordic_invk32 = 32'd2608131496; // 1/K = 0.607252935009
    32: cordic_invk32 = 32'd2608131496; // 1/K = 0.607252935009
    default: cordic_invk32 = 32'd0;
  endcase
endfunction
