function export_vectors(op)
%EXPORT_VECTORS  Golden CSVs for tb/tb_cordic_sweep.sv.
%
% One file per configuration: the chosen operating point plus the four
% N_ITER values used by the synthesis sweep (all at the operating-point word
% length, so the PPA table and the verification cover the same hardware).
% Columns: seq,mode,x,y,z,xo,yo,zo -- raw signed integers.
    if nargin < 1, op = struct('N', 15, 'W', 17); end
    cfgs = unique([op.N op.W; 8 op.W; 12 op.W; 16 op.W; 20 op.W], 'rows', 'stable');
    for k = 1:size(cfgs, 1)
        write_cfg(cfgs(k,1), cfgs(k,2));
    end
    f = fopen(fullfile('..', 'tb', 'vectors', 'operating_point.mk'), 'w');
    fprintf(f, '# GENERATED by matlab/export_vectors.m from the quantisation sweep\n');
    fprintf(f, 'OP_N := %d\nOP_W := %d\n', op.N, op.W);
    fclose(f);
end

function write_cfg(N, W)
    rng(N * 100 + W);
    F = W - 2;  FS = 2^(W-1);  one = 2^F;
    ri = @(n, lo, hi) randi([lo hi], n, 1);

    % rotation: full-circle sweep at unit amplitude (sin/cos use case)
    M = 4096;  k = (0:M-1)';
    z1 = round((k / M * 2 - 1) * FS);
    A = [zeros(M,1), one*ones(M,1), zeros(M,1), z1];
    % rotation: random in-range vectors (|v| <= 1.0) and random angles
    n = 2048;  r = rand(n,1);  t = rand(n,1) * 2*pi;
    A = [A; zeros(n,1), round(r.*cos(t)*one), round(r.*sin(t)*one), ri(n, -FS, FS-1)];
    % rotation: full-range random inputs -- exercises output saturation
    A = [A; zeros(n,1), ri(n, -FS, FS-1), ri(n, -FS, FS-1), ri(n, -FS, FS-1)];
    % vectoring: circles at several radii, all four quadrants
    for rad = [1.0 0.5 0.05 1.4]
        t = (k(1:4:end) + 0.37) / M * 2*pi;
        A = [A; ones(numel(t),1), round(rad*cos(t)*one), round(rad*sin(t)*one), zeros(numel(t),1)]; %#ok<AGROW>
    end
    % vectoring: full-range random (magnitude saturates), random z offset
    A = [A; ones(n,1), ri(n, -FS, FS-1), ri(n, -FS, FS-1), ri(n, -FS, FS-1)];
    % corners, both modes: zero, rails, axes, quadrant boundaries, convergence limit
    v = [0 1 -1 one -one FS-1 -FS];
    q = [0 1 -1 FS/2 FS/2-1 FS/2+1 -FS/2 -FS/2-1 -FS/2+1 FS-1 -FS ...
         round(1.7432866/pi*FS) -round(1.7432866/pi*FS)];
    [vx, vy, vz, vm] = ndgrid(v, v, q, [0 1]);
    A = [A; vm(:), vx(:), vy(:), vz(:)];

    [xo, yo, zo] = cordic_fixed(A(:,1), A(:,2), A(:,3), A(:,4), N, W);
    name = fullfile('..', 'tb', 'vectors', sprintf('cordic_N%d_W%d.csv', N, W));
    f = fopen(name, 'w');
    fprintf(f, 'seq,mode,x,y,z,xo,yo,zo\n');
    fprintf(f, '%d,%d,%d,%d,%d,%d,%d,%d\n', [(0:size(A,1)-1)', A, xo, yo, zo]');
    fclose(f);
    nsat = sum(abs(xo) >= FS-1 | abs(yo) >= FS-1 | xo == -FS | yo == -FS);
    fprintf('wrote %s  (%d vectors, %d hit a saturation rail)\n', name, size(A,1), nsat);
end
