function gen_atan_lut()
%GEN_ATAN_LUT  Write rtl/cordic_atan_lut.svh from cordic_consts().
    c = cordic_consts();
    f = fopen(fullfile('..', 'rtl', 'cordic_atan_lut.svh'), 'w');
    fprintf(f, '// GENERATED by matlab/gen_atan_lut.m -- do not edit by hand.\n');
    fprintf(f, '//\n');
    fprintf(f, '// cordic_atan32(i) = round(atan(2^-i) / pi * 2^31)   binary angle, pi == 2^31\n');
    fprintf(f, '// cordic_invk32(n) = round(2^32 / K_n)               K_n = prod_{i<n} sqrt(1 + 2^-2i)\n');
    fprintf(f, '//\n');
    fprintf(f, '// Functions rather than localparam arrays: Icarus Verilog does not accept\n');
    fprintf(f, '// ''{...} initialisers on unpacked arrays. Include inside a module body.\n\n');
    fprintf(f, 'function automatic [31:0] cordic_atan32(input integer i);\n  case (i)\n');
    for i = 0:31
        fprintf(f, '    %2d: cordic_atan32 = 32''d%-10d; // %.12f rad\n', i, c.atan32(i+1), atan(2^-i));
    end
    fprintf(f, '    default: cordic_atan32 = 32''d0;\n  endcase\nendfunction\n\n');
    fprintf(f, 'function automatic [31:0] cordic_invk32(input integer n);\n  case (n)\n');
    for n = 1:32
        fprintf(f, '    %2d: cordic_invk32 = 32''d%-10d; // 1/K = %.12f\n', n, c.invk32(n), 1/c.K(n));
    end
    fprintf(f, '    default: cordic_invk32 = 32''d0;\n  endcase\nendfunction\n');
    fclose(f);
    fprintf('wrote rtl/cordic_atan_lut.svh\n');
end
